[tool.poetry]
name = "my-python-project"
version = "0.1.0"
description = "A Python project template"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
