set shell := ["bash", "-c"]

re:
  direnv reload

up:
  nix flake update

qt:
  jupyter qtconsole &

test:
  pytest

tco:
  pytest --cov=src

repl:
  nix repl -f flake:nixpkgs

show:
  nix flake show

run:
  nix run .#default

build:
  nix build .#default

dockerbuild:
  nix build .#container

dockerrun:
  docker load < ./result
  # For streamLayeredImage
  # ./result | docker image load
  docker run -it --rm prj_name:latest
